SELECT COUNT(*)
FROM CITY
WHERE POPULATION > 100000;

SELECT SUM(POPULATION)
FROM CITY 
WHERE DISTRICT='California';

SELECT
    ROUND(AVG(POPULATION))
FROM CITY
WHERE DISTRICT = 'California';

SELECT
    ROUND(AVG(POPULATION))
FROM CITY;