SELECT *
FROM CITY
WHERE POPULATION > 100000
AND CountryCode = 'USA';

SELECT NAME
FROM CITY
WHERE POPULATION > 120000
AND CountryCode = 'USA';

SELECT * FROM CITY WHERE ID=1661;

SELECT * FROM CITY WHERE COUNTRYCODE='JPN';

SELECT CITY,STATE FROM STATION;

SELECT DISTINCT CITY FROM STATION WHERE ID % 2 = 0;

SELECT 
    COUNT(CITY) - COUNT(DISTINCT CITY)
FROM STATION;

SELECT * FROM (
    SELECT CITY, LENGTH(CITY) 
    FROM STATION
    ORDER BY LENGTH(CITY) ASC, CITY ASC
    LIMIT 1
) a
UNION
SELECT * FROM (
    SELECT CITY, LENGTH(CITY) 
    FROM STATION
    ORDER BY LENGTH(CITY) DESC, CITY ASC
    LIMIT 1
) b;