SELECT *
FROM CITY
WHERE POPULATION > 100000
AND CountryCode = 'USA';

SELECT NAME
FROM CITY
WHERE POPULATION > 120000
AND CountryCode = 'USA';

SELECT * FROM CITY WHERE ID=1661;

SELECT * FROM CITY WHERE COUNTRYCODE='JPN';

SELECT CITY,STATE FROM STATION;

SELECT DISTINCT CITY FROM STATION WHERE ID % 2 = 0;

SELECT 
    COUNT(CITY) - COUNT(DISTINCT CITY)
FROM STATION;

SELECT * FROM (
    SELECT CITY, LENGTH(CITY) 
    FROM STATION
    ORDER BY LENGTH(CITY) ASC, CITY ASC
    LIMIT 1
) a
UNION
SELECT * FROM (
    SELECT CITY, LENGTH(CITY) 
    FROM STATION
    ORDER BY LENGTH(CITY) DESC, CITY ASC
    LIMIT 1
) b;

SELECT
    DISTINCT CITY
FROM STATION
WHERE LOWER(LEFT(CITY,1)) IN ('a','e','i','o','u');

SELECT
    DISTINCT CITY
FROM STATION
WHERE LOWER(RIGHT(CITY,1)) IN ('a','e','i','o','u');


SELECT
    DISTINCT CITY
FROM STATION
WHERE LOWER(LEFT(CITY,1)) IN ('a','e','i','o','u')
AND LOWER(RIGHT(CITY,1)) IN ('a','e','i','o','u');